
version: '3.8'

services:
  flask-app:
    build:
      
      dockerfile: Dockerfile.conversation
    container_name: my-flask-conversation-container
    networks:
      - app-network

networks:
  app-network:
    external: true
