
version: '3.8'

services:
  flask-app:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: flask_app_container
    networks:
      - app-network

networks:
  app-network:
    external: true
